local colors = require("autumn_night.palette")

local M = {}

local groups = {
  AutumnFg0 = { fg = colors.fg0 },
  AutumnFg1 = { fg = colors.fg1 },
  AutumnFg2 = { fg = colors.fg2 },
  AutumnFg3 = { fg = colors.fg3 },
  AutumnFg4 = { fg = colors.fg4 },
  AutumnGray = { fg = colors.gray },
  AutumnBg0 = { fg = colors.bg0 },
  AutumnBg1 = { fg = colors.bg1 },
  AutumnBg2 = { fg = colors.bg2 },
  AutumnBg3 = { fg = colors.bg3 },
  AutumnBg4 = { fg = colors.bg4 },
  AutumnRed = { fg = colors.red },
  AutumnRedBold = { fg = colors.red },
  AutumnGreen = { fg = colors.green },
  AutumnGreenBold = { fg = colors.green },
  AutumnYellow = { fg = colors.yellow },
  AutumnYellowBold = { fg = colors.yellow },
  AutumnBlue = { fg = colors.blue },
  AutumnBlueBold = { fg = colors.blue },
  AutumnPurple = { fg = colors.purple },
  AutumnPurpleBold = { fg = colors.purple },
  AutumnAqua = { fg = colors.aqua },
  AutumnAquaBold = { fg = colors.aqua },
  AutumnOrange = { fg = colors.orange },
  AutumnOrangeBold = { fg = colors.orange },
  AutumnRedSign = { fg = colors.red, bg = colors.bg1 },
  AutumnGreenSign = { fg = colors.green, bg = colors.bg1 },
  AutumnYellowSign = { fg = colors.yellow, bg = colors.bg1 },
  AutumnBlueSign = { fg = colors.blue, bg = colors.bg1 },
  AutumnPurpleSign = { fg = colors.purple, bg = colors.bg1 },
  AutumnAquaSign = { fg = colors.aqua, bg = colors.bg1 },
  AutumnOrangeSign = { fg = colors.orange, bg = colors.bg1 },
  AutumnRedUnderline = { sp = colors.red },
  AutumnGreenUnderline = { sp = colors.green },
  AutumnYellowUnderline = { sp = colors.yellow },
  AutumnBlueUnderline = { sp = colors.blue },
  AutumnPurpleUnderline = { sp = colors.purple },
  AutumnAquaUnderline = { sp = colors.aqua },
  AutumnOrangeUnderline = { sp = colors.orange },
  Normal = { fg = colors.fg1, bg = colors.bg0 },
  NormalFloat = { fg = colors.fg1, bg = colors.bg1 },
  NormalNC = { link = "Normal" },
  CursorLine = { bg = colors.bg1 },
  CursorColumn = { link = "CursorLine" },
  TabLineFill = { fg = colors.bg4, bg = colors.bg1 },
  TabLineSel = { fg = colors.green, bg = colors.bg1 },
  TabLine = { link = "TabLineFill" },
  MatchParen = { bg = colors.bg3 },
  ColorColumn = { bg = colors.bg1 },
  Conceal = { fg = colors.blue },
  CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
  NonText = { link = "AutumnBg2" },
  SpecialKey = { link = "AutumnFg4" },
  Visual = { bg = colors.bg3 },
  VisualNOS = { link = "Visual" },
  Search = { fg = colors.yellow, bg = colors.bg3 },
  IncSearch = { fg = colors.orange, bg = colors.bg3 },
  CurSearch = { link = "IncSearch" },
  QuickFixLine = { link = "AutumnPurple" },
  Underlined = { fg = colors.blue },
  StatusLine = { fg = colors.bg2, bg = colors.neutral_blue },
  StatusLineNC = { fg = colors.bg1, bg = colors.fg4 },
  WinBar = { fg = colors.fg4, bg = colors.bg0 },
  WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
  WinSeparator = { fg = colors.bg3, bg = colors.bg0 },
  WildMenu = { fg = colors.blue, bg = colors.bg2 },
  Directory = { link = "AutumnGreenBold" },
  Title = { link = "AutumnGreenBold" },
  ErrorMsg = { fg = colors.bg0, bg = colors.red },
  MoreMsg = { link = "AutumnYellowBold" },
  ModeMsg = { link = "AutumnYellowBold" },
  Question = { link = "AutumnOrangeBold" },
  WarningMsg = { link = "AutumnRedBold" },
  LineNr = { fg = colors.bg4 },
  SignColumn = { bg = colors.bg1 },
  Folded = { fg = colors.gray, bg = colors.bg1 },
  FoldColumn = { fg = colors.gray, bg = colors.bg1 },
  vCursor = { link = "Cursor" },
  iCursor = { link = "Cursor" },
  lCursor = { link = "Cursor" },
  Special = { link = "AutumnYellow" },
  Comment = { fg = colors.gray },
  Todo = { fg = colors.bg0, bg = colors.yellow },
  Done = { fg = colors.orange },
  Error = { fg = colors.red },
  Statement = { link = "AutumnRed" },
  Conditional = { link = "AutumnRed" },
  Repeat = { link = "AutumnRed" },
  Label = { link = "AutumnRed" },
  Exception = { link = "AutumnRed" },
  Operator = { fg = colors.orange },
  Keyword = { link = "AutumnRed" },
  Identifier = { link = "AutumnOrange" },
  Function = { link = "AutumnYellow" },
  PreProc = { link = "AutumnAqua" },
  Include = { link = "AutumnAqua" },
  Define = { link = "AutumnAqua" },
  Macro = { link = "AutumnAqua" },
  PreCondit = { link = "AutumnAqua" },
  Constant = { link = "AutumnPurple" },
  Character = { link = "AutumnPurple" },
  String = { fg = colors.green },
  Boolean = { link = "AutumnPurple" },
  Number = { link = "AutumnPurple" },
  Float = { link = "AutumnPurple" },
  Type = { link = "AutumnYellow" },
  StorageClass = { link = "AutumnOrange" },
  Structure = { link = "AutumnAqua" },
  Typedef = { link = "AutumnYellow" },
  Pmenu = { fg = colors.fg1, bg = colors.bg2 },
  PmenuSel = { fg = colors.bg2, bg = colors.blue },
  PmenuSbar = { bg = colors.bg2 },
  PmenuThumb = { bg = colors.bg4 },
  DiffDelete = { bg = colors.dark_red },
  DiffAdd = { bg = colors.dark_green },
  DiffChange = { bg = colors.dark_aqua },
  DiffText = { bg = colors.yellow, fg = colors.bg0 },
  SpellCap = { link = "AutumnBlueUnderline" },
  SpellBad = { link = "AutumnRedUnderline" },
  SpellLocal = { link = "AutumnAquaUnderline" },
  SpellRare = { link = "AutumnPurpleUnderline" },
  Whitespace = { fg = colors.bg2 },
  Delimiter = { link = "AutumnOrange" },
  EndOfBuffer = { link = "NonText" },
  DiagnosticError = { link = "AutumnRed" },
  DiagnosticSignError = { link = "AutumnRedSign" },
  DiagnosticUnderlineError = { link = "AutumnRedUnderline" },
  DiagnosticWarn = { link = "AutumnYellow" },
  DiagnosticSignWarn = { link = "AutumnYellowSign" },
  DiagnosticUnderlineWarn = { link = "AutumnYellowUnderline" },
  DiagnosticInfo = { link = "AutumnBlue" },
  DiagnosticSignInfo = { link = "AutumnBlueSign" },
  DiagnosticUnderlineInfo = { link = "AutumnBlueUnderline" },
  DiagnosticHint = { link = "AutumnAqua" },
  DiagnosticSignHint = { link = "AutumnAquaSign" },
  DiagnosticUnderlineHint = { link = "AutumnAquaUnderline" },
  DiagnosticFloatingError = { link = "AutumnRed" },
  DiagnosticFloatingWarn = { link = "AutumnOrange" },
  DiagnosticFloatingInfo = { link = "AutumnBlue" },
  DiagnosticFloatingHint = { link = "AutumnAqua" },
  DiagnosticVirtualTextError = { link = "AutumnRed" },
  DiagnosticVirtualTextWarn = { link = "AutumnYellow" },
  DiagnosticVirtualTextInfo = { link = "AutumnBlue" },
  DiagnosticVirtualTextHint = { link = "AutumnAqua" },
  DiagnosticOk = { link = "AutumnGreenSign" },
  LspReferenceRead = { link = "AutumnYellowBold" },
  LspReferenceText = { link = "AutumnYellowBold" },
  LspReferenceWrite = { link = "AutumnOrangeBold" },
  LspCodeLens = { link = "AutumnGray" },
  LspSignatureActiveParameter = { link = "Search" },
  gitcommitSelectedFile = { link = "AutumnGreen" },
  gitcommitDiscardedFile = { link = "AutumnRed" },
  GitSignsAdd = { link = "AutumnGreen" },
  GitSignsChange = { link = "AutumnOrange" },
  GitSignsDelete = { link = "AutumnRed" },
  NvimTreeSymlink = { fg = colors.neutral_aqua },
  NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
  NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
  NvimTreeFileIcon = { fg = colors.fg2 },
  NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
  NvimTreeOpenedFile = { fg = colors.red, bold = true },
  NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
  NvimTreeImageFile = { fg = colors.neutral_purple },
  NvimTreeIndentMarker = { fg = colors.bg3 },
  NvimTreeGitDirty = { fg = colors.neutral_yellow },
  NvimTreeGitStaged = { fg = colors.neutral_yellow },
  NvimTreeGitMerge = { fg = colors.neutral_purple },
  NvimTreeGitRenamed = { fg = colors.neutral_purple },
  NvimTreeGitNew = { fg = colors.neutral_yellow },
  NvimTreeGitDeleted = { fg = colors.neutral_red },
  NvimTreeWindowPicker = { bg = colors.aqua },
  debugPC = { link = "DiffAdd" },
  debugBreakpoint = { link = "AutumnRedSign" },
  StartifyBracket = { link = "AutumnFg3" },
  StartifyFile = { link = "AutumnFg1" },
  StartifyNumber = { link = "AutumnBlue" },
  StartifyPath = { link = "AutumnGray" },
  StartifySlash = { link = "AutumnGray" },
  StartifySection = { link = "AutumnYellow" },
  StartifySpecial = { link = "AutumnBg2" },
  StartifyHeader = { link = "AutumnOrange" },
  StartifyFooter = { link = "AutumnBg2" },
  StartifyVar = { link = "StartifyPath" },
  StartifySelect = { link = "Title" },
  DirvishPathTail = { link = "AutumnAqua" },
  DirvishArg = { link = "AutumnYellow" },
  netrwDir = { link = "AutumnAqua" },
  netrwClassify = { link = "AutumnAqua" },
  netrwLink = { link = "AutumnGray" },
  netrwSymLink = { link = "AutumnFg1" },
  netrwExe = { link = "AutumnYellow" },
  netrwComment = { link = "AutumnGray" },
  netrwList = { link = "AutumnBlue" },
  netrwHelpCmd = { link = "AutumnAqua" },
  netrwCmdSep = { link = "AutumnFg3" },
  netrwVersion = { link = "AutumnGreen" },
  NERDTreeDir = { link = "AutumnAqua" },
  NERDTreeDirSlash = { link = "AutumnAqua" },
  NERDTreeOpenable = { link = "AutumnOrange" },
  NERDTreeClosable = { link = "AutumnOrange" },
  NERDTreeFile = { link = "AutumnFg1" },
  NERDTreeExecFile = { link = "AutumnYellow" },
  NERDTreeUp = { link = "AutumnGray" },
  NERDTreeCWD = { link = "AutumnGreen" },
  NERDTreeHelp = { link = "AutumnFg1" },
  NERDTreeToggleOn = { link = "AutumnGreen" },
  NERDTreeToggleOff = { link = "AutumnRed" },
  CocErrorSign = { link = "AutumnRedSign" },
  CocWarningSign = { link = "AutumnOrangeSign" },
  CocInfoSign = { link = "AutumnBlueSign" },
  CocHintSign = { link = "AutumnAquaSign" },
  CocErrorFloat = { link = "AutumnRed" },
  CocWarningFloat = { link = "AutumnOrange" },
  CocInfoFloat = { link = "AutumnBlue" },
  CocHintFloat = { link = "AutumnAqua" },
  CocDiagnosticsError = { link = "AutumnRed" },
  CocDiagnosticsWarning = { link = "AutumnOrange" },
  CocDiagnosticsInfo = { link = "AutumnBlue" },
  CocDiagnosticsHint = { link = "AutumnAqua" },
  CocSearch = { link = "AutumnBlue" },
  CocSelectedText = { link = "AutumnRed" },
  CocMenuSel = { link = "PmenuSel" },
  CocCodeLens = { link = "AutumnGray" },
  CocErrorHighlight = { link = "AutumnRedUnderline" },
  CocWarningHighlight = { link = "AutumnOrangeUnderline" },
  CocInfoHighlight = { link = "AutumnBlueUnderline" },
  CocHintHighlight = { link = "AutumnAquaUnderline" },
  TelescopeNormal = { link = "AutumnFg1" },
  TelescopeSelection = { link = "AutumnOrangeBold" },
  TelescopeSelectionCaret = { link = "AutumnRed" },
  TelescopeMultiSelection = { link = "AutumnGray" },
  TelescopeBorder = { link = "TelescopeNormal" },
  TelescopePromptBorder = { link = "TelescopeNormal" },
  TelescopeResultsBorder = { link = "TelescopeNormal" },
  TelescopePreviewBorder = { link = "TelescopeNormal" },
  TelescopeMatching = { link = "AutumnBlue" },
  TelescopePromptPrefix = { link = "AutumnRed" },
  TelescopePrompt = { link = "TelescopeNormal" },
  CmpItemAbbr = { link = "AutumnFg0" },
  CmpItemAbbrDeprecated = { link = "AutumnFg1" },
  CmpItemAbbrMatch = { link = "AutumnBlueBold" },
  CmpItemAbbrMatchFuzzy = { link = "AutumnBlueUnderline" },
  CmpItemMenu = { link = "AutumnGray" },
  CmpItemKindText = { link = "AutumnOrange" },
  CmpItemKindVariable = { link = "AutumnOrange" },
  CmpItemKindMethod = { link = "AutumnBlue" },
  CmpItemKindFunction = { link = "AutumnBlue" },
  CmpItemKindConstructor = { link = "AutumnYellow" },
  CmpItemKindUnit = { link = "AutumnBlue" },
  CmpItemKindField = { link = "AutumnBlue" },
  CmpItemKindClass = { link = "AutumnYellow" },
  CmpItemKindInterface = { link = "AutumnYellow" },
  CmpItemKindModule = { link = "AutumnBlue" },
  CmpItemKindProperty = { link = "AutumnBlue" },
  CmpItemKindValue = { link = "AutumnOrange" },
  CmpItemKindEnum = { link = "AutumnYellow" },
  CmpItemKindOperator = { link = "AutumnYellow" },
  CmpItemKindKeyword = { link = "AutumnPurple" },
  CmpItemKindEvent = { link = "AutumnPurple" },
  CmpItemKindReference = { link = "AutumnPurple" },
  CmpItemKindColor = { link = "AutumnPurple" },
  CmpItemKindSnippet = { link = "AutumnGreen" },
  CmpItemKindFile = { link = "AutumnBlue" },
  CmpItemKindFolder = { link = "AutumnBlue" },
  CmpItemKindEnumMember = { link = "AutumnAqua" },
  CmpItemKindConstant = { link = "AutumnOrange" },
  CmpItemKindStruct = { link = "AutumnYellow" },
  CmpItemKindTypeParameter = { link = "AutumnYellow" },
  BlinkCmpLabel = { link = "AutumnFg0" },
  BlinkCmpLabelDeprecated = { link = "AutumnFg1" },
  BlinkCmpLabelMatch = { link = "AutumnBlueBold" },
  BlinkCmpLabelDetail = { link = "AutumnGray" },
  BlinkCmpLabelDescription = { link = "AutumnGray" },
  BlinkCmpKindText = { link = "AutumnOrange" },
  BlinkCmpKindVariable = { link = "AutumnOrange" },
  BlinkCmpKindMethod = { link = "AutumnBlue" },
  BlinkCmpKindFunction = { link = "AutumnBlue" },
  BlinkCmpKindConstructor = { link = "AutumnYellow" },
  BlinkCmpKindUnit = { link = "AutumnBlue" },
  BlinkCmpKindField = { link = "AutumnBlue" },
  BlinkCmpKindClass = { link = "AutumnYellow" },
  BlinkCmpKindInterface = { link = "AutumnYellow" },
  BlinkCmpKindModule = { link = "AutumnBlue" },
  BlinkCmpKindProperty = { link = "AutumnBlue" },
  BlinkCmpKindValue = { link = "AutumnOrange" },
  BlinkCmpKindEnum = { link = "AutumnYellow" },
  BlinkCmpKindOperator = { link = "AutumnYellow" },
  BlinkCmpKindKeyword = { link = "AutumnPurple" },
  BlinkCmpKindEvent = { link = "AutumnPurple" },
  BlinkCmpKindReference = { link = "AutumnPurple" },
  BlinkCmpKindColor = { link = "AutumnPurple" },
  BlinkCmpKindSnippet = { link = "AutumnGreen" },
  BlinkCmpKindFile = { link = "AutumnBlue" },
  BlinkCmpKindFolder = { link = "AutumnBlue" },
  BlinkCmpKindEnumMember = { link = "AutumnAqua" },
  BlinkCmpKindConstant = { link = "AutumnOrange" },
  BlinkCmpKindStruct = { link = "AutumnYellow" },
  BlinkCmpKindTypeParameter = { link = "AutumnYellow" },
  BlinkCmpSource = { link = "AutumnGray" },
  BlinkCmpGhostText = { link = "AutumnBg4" },
  diffAdded = { link = "DiffAdd" },
  diffRemoved = { link = "DiffDelete" },
  diffChanged = { link = "DiffChange" },
  diffFile = { link = "AutumnOrange" },
  diffNewFile = { link = "AutumnYellow" },
  diffOldFile = { link = "AutumnOrange" },
  diffLine = { link = "AutumnBlue" },
  diffIndexLine = { link = "diffChanged" },
  NavicIconsFile = { link = "AutumnBlue" },
  NavicIconsModule = { link = "AutumnOrange" },
  NavicIconsNamespace = { link = "AutumnBlue" },
  NavicIconsPackage = { link = "AutumnAqua" },
  NavicIconsClass = { link = "AutumnYellow" },
  NavicIconsMethod = { link = "AutumnBlue" },
  NavicIconsProperty = { link = "AutumnAqua" },
  NavicIconsField = { link = "AutumnPurple" },
  NavicIconsConstructor = { link = "AutumnBlue" },
  NavicIconsEnum = { link = "AutumnPurple" },
  NavicIconsInterface = { link = "AutumnGreen" },
  NavicIconsFunction = { link = "AutumnBlue" },
  NavicIconsVariable = { link = "AutumnPurple" },
  NavicIconsConstant = { link = "AutumnOrange" },
  NavicIconsString = { link = "AutumnGreen" },
  NavicIconsNumber = { link = "AutumnOrange" },
  NavicIconsBoolean = { link = "AutumnOrange" },
  NavicIconsArray = { link = "AutumnOrange" },
  NavicIconsObject = { link = "AutumnOrange" },
  NavicIconsKey = { link = "AutumnAqua" },
  NavicIconsNull = { link = "AutumnOrange" },
  NavicIconsEnumMember = { link = "AutumnYellow" },
  NavicIconsStruct = { link = "AutumnPurple" },
  NavicIconsEvent = { link = "AutumnYellow" },
  NavicIconsOperator = { link = "AutumnRed" },
  NavicIconsTypeParameter = { link = "AutumnRed" },
  NavicText = { link = "AutumnWhite" },
  NavicSeparator = { link = "AutumnWhite" },
  htmlTag = { link = "AutumnAquaBold" },
  htmlEndTag = { link = "AutumnAquaBold" },
  htmlTagName = { link = "AutumnBlue" },
  htmlArg = { link = "AutumnOrange" },
  htmlTagN = { link = "AutumnFg1" },
  htmlSpecialTagName = { link = "AutumnBlue" },
  htmlLink = { fg = colors.fg4 },
  htmlSpecialChar = { link = "AutumnRed" },
  htmlBold = { fg = colors.fg0, bg = colors.bg0 },
  htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0 },
  htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0 },
  htmlBoldUnderlineItalic = {
    fg = colors.fg0,
    bg = colors.bg0,
    italic = true,
  },
  htmlUnderline = { fg = colors.fg0, bg = colors.bg0 },
  htmlUnderlineItalic = {
    fg = colors.fg0,
    bg = colors.bg0,
    italic = true,
  },
  htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
  xmlTag = { link = "AutumnAquaBold" },
  xmlEndTag = { link = "AutumnAquaBold" },
  xmlTagName = { link = "AutumnBlue" },
  xmlEqual = { link = "AutumnBlue" },
  docbkKeyword = { link = "AutumnAquaBold" },
  xmlDocTypeDecl = { link = "AutumnGray" },
  xmlDocTypeKeyword = { link = "AutumnPurple" },
  xmlCdataStart = { link = "AutumnGray" },
  xmlCdataCdata = { link = "AutumnPurple" },
  dtdFunction = { link = "AutumnGray" },
  dtdTagName = { link = "AutumnPurple" },
  xmlAttrib = { link = "AutumnOrange" },
  xmlProcessingDelim = { link = "AutumnGray" },
  dtdParamEntityPunct = { link = "AutumnGray" },
  dtdParamEntityDPunct = { link = "AutumnGray" },
  xmlAttribPunct = { link = "AutumnGray" },
  xmlEntity = { link = "AutumnRed" },
  xmlEntityPunct = { link = "AutumnRed" },
  clojureKeyword = { link = "AutumnBlue" },
  clojureCond = { link = "AutumnOrange" },
  clojureSpecial = { link = "AutumnOrange" },
  clojureDefine = { link = "AutumnOrange" },
  clojureFunc = { link = "AutumnYellow" },
  clojureRepeat = { link = "AutumnYellow" },
  clojureCharacter = { link = "AutumnAqua" },
  clojureStringEscape = { link = "AutumnAqua" },
  clojureException = { link = "AutumnRed" },
  clojureRegexp = { link = "AutumnAqua" },
  clojureRegexpEscape = { link = "AutumnAqua" },
  clojureRegexpCharClass = { fg = colors.fg3 },
  clojureRegexpMod = { link = "clojureRegexpCharClass" },
  clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
  clojureParen = { link = "AutumnFg3" },
  clojureAnonArg = { link = "AutumnYellow" },
  clojureVariable = { link = "AutumnBlue" },
  clojureMacro = { link = "AutumnOrange" },
  clojureMeta = { link = "AutumnYellow" },
  clojureDeref = { link = "AutumnYellow" },
  clojureQuote = { link = "AutumnYellow" },
  clojureUnquote = { link = "AutumnYellow" },
  cOperator = { link = "AutumnPurple" },
  cppOperator = { link = "AutumnPurple" },
  cStructure = { link = "AutumnOrange" },
  pythonBuiltin = { link = "AutumnOrange" },
  pythonBuiltinObj = { link = "AutumnOrange" },
  pythonBuiltinFunc = { link = "AutumnOrange" },
  pythonFunction = { link = "AutumnAqua" },
  pythonDecorator = { link = "AutumnRed" },
  pythonInclude = { link = "AutumnBlue" },
  pythonImport = { link = "AutumnBlue" },
  pythonRun = { link = "AutumnBlue" },
  pythonCoding = { link = "AutumnBlue" },
  pythonOperator = { link = "AutumnRed" },
  pythonException = { link = "AutumnRed" },
  pythonExceptions = { link = "AutumnPurple" },
  pythonBoolean = { link = "AutumnPurple" },
  pythonDot = { link = "AutumnFg3" },
  pythonConditional = { link = "AutumnRed" },
  pythonRepeat = { link = "AutumnRed" },
  pythonDottedName = { link = "AutumnGreenBold" },
  cssBraces = { link = "AutumnBlue" },
  cssFunctionName = { link = "AutumnYellow" },
  cssIdentifier = { link = "AutumnOrange" },
  cssClassName = { link = "AutumnGreen" },
  cssColor = { link = "AutumnBlue" },
  cssSelectorOp = { link = "AutumnBlue" },
  cssSelectorOp2 = { link = "AutumnBlue" },
  cssImportant = { link = "AutumnGreen" },
  cssVendor = { link = "AutumnFg1" },
  cssTextProp = { link = "AutumnAqua" },
  cssAnimationProp = { link = "AutumnAqua" },
  cssUIProp = { link = "AutumnYellow" },
  cssTransformProp = { link = "AutumnAqua" },
  cssTransitionProp = { link = "AutumnAqua" },
  cssPrintProp = { link = "AutumnAqua" },
  cssPositioningProp = { link = "AutumnYellow" },
  cssBoxProp = { link = "AutumnAqua" },
  cssFontDescriptorProp = { link = "AutumnAqua" },
  cssFlexibleBoxProp = { link = "AutumnAqua" },
  cssBorderOutlineProp = { link = "AutumnAqua" },
  cssBackgroundProp = { link = "AutumnAqua" },
  cssMarginProp = { link = "AutumnAqua" },
  cssListProp = { link = "AutumnAqua" },
  cssTableProp = { link = "AutumnAqua" },
  cssFontProp = { link = "AutumnAqua" },
  cssPaddingProp = { link = "AutumnAqua" },
  cssDimensionProp = { link = "AutumnAqua" },
  cssRenderProp = { link = "AutumnAqua" },
  cssColorProp = { link = "AutumnAqua" },
  cssGeneratedContentProp = { link = "AutumnAqua" },
  javaScriptBraces = { link = "AutumnFg1" },
  javaScriptFunction = { link = "AutumnAqua" },
  javaScriptIdentifier = { link = "AutumnRed" },
  javaScriptMember = { link = "AutumnBlue" },
  javaScriptNumber = { link = "AutumnPurple" },
  javaScriptNull = { link = "AutumnPurple" },
  javaScriptParens = { link = "AutumnFg3" },
  typescriptReserved = { link = "AutumnAqua" },
  typescriptLabel = { link = "AutumnAqua" },
  typescriptFuncKeyword = { link = "AutumnAqua" },
  typescriptIdentifier = { link = "AutumnOrange" },
  typescriptBraces = { link = "AutumnFg1" },
  typescriptEndColons = { link = "AutumnFg1" },
  typescriptDOMObjects = { link = "AutumnFg1" },
  typescriptAjaxMethods = { link = "AutumnFg1" },
  typescriptLogicSymbols = { link = "AutumnFg1" },
  typescriptDocSeeTag = { link = "Comment" },
  typescriptDocParam = { link = "Comment" },
  typescriptDocTags = { link = "vimCommentTitle" },
  typescriptGlobalObjects = { link = "AutumnFg1" },
  typescriptParens = { link = "AutumnFg3" },
  typescriptOpSymbols = { link = "AutumnFg3" },
  typescriptHtmlElemProperties = { link = "AutumnFg1" },
  typescriptNull = { link = "AutumnPurple" },
  typescriptInterpolationDelimiter = { link = "AutumnAqua" },
  purescriptModuleKeyword = { link = "AutumnAqua" },
  purescriptModuleName = { link = "AutumnFg1" },
  purescriptWhere = { link = "AutumnAqua" },
  purescriptDelimiter = { link = "AutumnFg4" },
  purescriptType = { link = "AutumnFg1" },
  purescriptImportKeyword = { link = "AutumnAqua" },
  purescriptHidingKeyword = { link = "AutumnAqua" },
  purescriptAsKeyword = { link = "AutumnAqua" },
  purescriptStructure = { link = "AutumnAqua" },
  purescriptOperator = { link = "AutumnBlue" },
  purescriptTypeVar = { link = "AutumnFg1" },
  purescriptConstructor = { link = "AutumnFg1" },
  purescriptFunction = { link = "AutumnFg1" },
  purescriptConditional = { link = "AutumnOrange" },
  purescriptBacktick = { link = "AutumnOrange" },
  coffeeExtendedOp = { link = "AutumnFg3" },
  coffeeSpecialOp = { link = "AutumnFg3" },
  coffeeCurly = { link = "AutumnOrange" },
  coffeeParen = { link = "AutumnFg3" },
  coffeeBracket = { link = "AutumnOrange" },
  rubyStringDelimiter = { link = "AutumnGreen" },
  rubyInterpolationDelimiter = { link = "AutumnAqua" },
  rubyDefinedOperator = { link = "rubyKeyword" },
  objcTypeModifier = { link = "AutumnRed" },
  objcDirective = { link = "AutumnBlue" },
  goDirective = { link = "AutumnAqua" },
  goConstants = { link = "AutumnPurple" },
  goDeclaration = { link = "AutumnRed" },
  goDeclType = { link = "AutumnBlue" },
  goBuiltins = { link = "AutumnOrange" },
  luaIn = { link = "AutumnRed" },
  luaFunction = { link = "AutumnAqua" },
  luaTable = { link = "AutumnOrange" },
  moonSpecialOp = { link = "AutumnFg3" },
  moonExtendedOp = { link = "AutumnFg3" },
  moonFunction = { link = "AutumnFg3" },
  moonObject = { link = "AutumnYellow" },
  javaAnnotation = { link = "AutumnBlue" },
  javaDocTags = { link = "AutumnAqua" },
  javaCommentTitle = { link = "vimCommentTitle" },
  javaParen = { link = "AutumnFg3" },
  javaParen1 = { link = "AutumnFg3" },
  javaParen2 = { link = "AutumnFg3" },
  javaParen3 = { link = "AutumnFg3" },
  javaParen4 = { link = "AutumnFg3" },
  javaParen5 = { link = "AutumnFg3" },
  javaOperator = { link = "AutumnOrange" },
  javaVarArg = { link = "AutumnGreen" },
  elixirDocString = { link = "Comment" },
  elixirStringDelimiter = { link = "AutumnGreen" },
  elixirInterpolationDelimiter = { link = "AutumnAqua" },
  elixirModuleDeclaration = { link = "AutumnYellow" },
  scalaNameDefinition = { link = "AutumnFg1" },
  scalaCaseFollowing = { link = "AutumnFg1" },
  scalaCapitalWord = { link = "AutumnFg1" },
  scalaTypeExtension = { link = "AutumnFg1" },
  scalaKeyword = { link = "AutumnRed" },
  scalaKeywordModifier = { link = "AutumnRed" },
  scalaSpecial = { link = "AutumnAqua" },
  scalaOperator = { link = "AutumnFg1" },
  scalaTypeDeclaration = { link = "AutumnYellow" },
  scalaTypeTypePostDeclaration = { link = "AutumnYellow" },
  scalaInstanceDeclaration = { link = "AutumnFg1" },
  scalaInterpolation = { link = "AutumnAqua" },
  markdownItalic = { fg = colors.fg3, italic = true },
  markdownBold = { fg = colors.fg3 },
  markdownBoldItalic = { fg = colors.fg3, italic = true },
  markdownH1 = { link = "AutumnGreenBold" },
  markdownH2 = { link = "AutumnGreenBold" },
  markdownH3 = { link = "AutumnYellowBold" },
  markdownH4 = { link = "AutumnYellowBold" },
  markdownH5 = { link = "AutumnYellow" },
  markdownH6 = { link = "AutumnYellow" },
  markdownCode = { link = "AutumnAqua" },
  markdownCodeBlock = { link = "AutumnAqua" },
  markdownCodeDelimiter = { link = "AutumnAqua" },
  markdownBlockquote = { link = "AutumnGray" },
  markdownListMarker = { link = "AutumnGray" },
  markdownOrderedListMarker = { link = "AutumnGray" },
  markdownRule = { link = "AutumnGray" },
  markdownHeadingRule = { link = "AutumnGray" },
  markdownUrlDelimiter = { link = "AutumnFg3" },
  markdownLinkDelimiter = { link = "AutumnFg3" },
  markdownLinkTextDelimiter = { link = "AutumnFg3" },
  markdownHeadingDelimiter = { link = "AutumnOrange" },
  markdownUrl = { link = "AutumnPurple" },
  markdownUrlTitleDelimiter = { link = "AutumnGreen" },
  markdownLinkText = { fg = colors.gray },
  markdownIdDeclaration = { link = "markdownLinkText" },
  haskellType = { link = "AutumnBlue" },
  haskellIdentifier = { link = "AutumnAqua" },
  haskellSeparator = { link = "AutumnFg4" },
  haskellDelimiter = { link = "AutumnOrange" },
  haskellOperators = { link = "AutumnPurple" },
  haskellBacktick = { link = "AutumnOrange" },
  haskellStatement = { link = "AutumnPurple" },
  haskellConditional = { link = "AutumnPurple" },
  haskellLet = { link = "AutumnRed" },
  haskellDefault = { link = "AutumnRed" },
  haskellWhere = { link = "AutumnRed" },
  haskellBottom = { link = "AutumnRedBold" },
  haskellImportKeywords = { link = "AutumnPurpleBold" },
  haskellDeclKeyword = { link = "AutumnOrange" },
  haskellDecl = { link = "AutumnOrange" },
  haskellDeriving = { link = "AutumnPurple" },
  haskellAssocType = { link = "AutumnAqua" },
  haskellNumber = { link = "AutumnAqua" },
  haskellPragma = { link = "AutumnRedBold" },
  haskellTH = { link = "AutumnAquaBold" },
  haskellForeignKeywords = { link = "AutumnGreen" },
  haskellKeyword = { link = "AutumnRed" },
  haskellFloat = { link = "AutumnAqua" },
  haskellInfix = { link = "AutumnPurple" },
  haskellQuote = { link = "AutumnGreenBold" },
  haskellShebang = { link = "AutumnYellowBold" },
  haskellLiquid = { link = "AutumnPurpleBold" },
  haskellQuasiQuoted = { link = "AutumnBlueBold" },
  haskellRecursiveDo = { link = "AutumnPurple" },
  haskellQuotedType = { link = "AutumnRed" },
  haskellPreProc = { link = "AutumnFg4" },
  haskellTypeRoles = { link = "AutumnRedBold" },
  haskellTypeForall = { link = "AutumnRed" },
  haskellPatternKeyword = { link = "AutumnBlue" },
  jsonKeyword = { link = "AutumnGreen" },
  jsonQuote = { link = "AutumnGreen" },
  jsonBraces = { link = "AutumnFg1" },
  jsonString = { link = "AutumnFg1" },
  mailQuoted1 = { link = "AutumnAqua" },
  mailQuoted2 = { link = "AutumnPurple" },
  mailQuoted3 = { link = "AutumnYellow" },
  mailQuoted4 = { link = "AutumnGreen" },
  mailQuoted5 = { link = "AutumnRed" },
  mailQuoted6 = { link = "AutumnOrange" },
  mailSignature = { link = "Comment" },
  csBraces = { link = "AutumnFg1" },
  csEndColon = { link = "AutumnFg1" },
  csLogicSymbols = { link = "AutumnFg1" },
  csParens = { link = "AutumnFg3" },
  csOpSymbols = { link = "AutumnFg3" },
  csInterpolationDelimiter = { link = "AutumnFg3" },
  csInterpolationAlignDel = { link = "AutumnAquaBold" },
  csInterpolationFormat = { link = "AutumnAqua" },
  csInterpolationFormatDel = { link = "AutumnAquaBold" },
  rustSigil = { link = "AutumnOrange" },
  rustEscape = { link = "AutumnAqua" },
  rustStringContinuation = { link = "AutumnAqua" },
  rustEnum = { link = "AutumnAqua" },
  rustStructure = { link = "AutumnAqua" },
  rustModPathSep = { link = "AutumnFg2" },
  rustCommentLineDoc = { link = "Comment" },
  rustDefault = { link = "AutumnAqua" },
  ocamlOperator = { link = "AutumnFg1" },
  ocamlKeyChar = { link = "AutumnOrange" },
  ocamlArrow = { link = "AutumnOrange" },
  ocamlInfixOpKeyword = { link = "AutumnRed" },
  ocamlConstructor = { link = "AutumnOrange" },
  LspSagaCodeActionTitle = { link = "Title" },
  LspSagaCodeActionBorder = { link = "AutumnFg1" },
  LspSagaCodeActionContent = { fg = colors.green },
  LspSagaLspFinderBorder = { link = "AutumnFg1" },
  LspSagaAutoPreview = { link = "AutumnOrange" },
  TargetWord = { fg = colors.blue },
  FinderSeparator = { link = "AutumnAqua" },
  LspSagaDefPreviewBorder = { link = "AutumnBlue" },
  LspSagaHoverBorder = { link = "AutumnOrange" },
  LspSagaRenameBorder = { link = "AutumnBlue" },
  LspSagaDiagnosticSource = { link = "AutumnOrange" },
  LspSagaDiagnosticBorder = { link = "AutumnPurple" },
  LspSagaDiagnosticHeader = { link = "AutumnGreen" },
  LspSagaSignatureHelpBorder = { link = "AutumnGreen" },
  SagaShadow = { link = "AutumnBg0" },
  DashboardShortCut = { link = "AutumnOrange" },
  DashboardHeader = { link = "AutumnAqua" },
  DashboardCenter = { link = "AutumnYellow" },
  DashboardFooter = { fg = colors.purple, italic = true },
  MasonHighlight = { link = "AutumnAqua" },
  MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
  MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
  MasonHighlightSecondary = { fg = colors.yellow },
  MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
  MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
  MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
  MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
  MasonMuted = { fg = colors.fg4 },
  MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
  MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
  LspInlayHint = { link = "AutumnGray" },
  CarbonFile = { link = "AutumnFg1" },
  CarbonExe = { link = "AutumnYellow" },
  CarbonSymlink = { link = "AutumnAqua" },
  CarbonBrokenSymlink = { link = "AutumnRed" },
  CarbonIndicator = { link = "AutumnGray" },
  CarbonDanger = { link = "AutumnRed" },
  CarbonPending = { link = "AutumnYellow" },
  NoiceCursor = { link = "TermCursor" },
  NoiceCmdlinePopupBorder = { fg = colors.blue, bg = nil },
  NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
  NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
  NoiceCmdlinePopupBorderSearch = { fg = colors.yellow, bg = nil },
  NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
  NotifyDEBUGBorder = { link = "AutumnBlue" },
  NotifyDEBUGIcon = { link = "AutumnBlue" },
  NotifyDEBUGTitle = { link = "AutumnBlue" },
  NotifyERRORBorder = { link = "AutumnRed" },
  NotifyERRORIcon = { link = "AutumnRed" },
  NotifyERRORTitle = { link = "AutumnRed" },
  NotifyINFOBorder = { link = "AutumnAqua" },
  NotifyINFOIcon = { link = "AutumnAqua" },
  NotifyINFOTitle = { link = "AutumnAqua" },
  NotifyTRACEBorder = { link = "AutumnGreen" },
  NotifyTRACEIcon = { link = "AutumnGreen" },
  NotifyTRACETitle = { link = "AutumnGreen" },
  NotifyWARNBorder = { link = "AutumnYellow" },
  NotifyWARNIcon = { link = "AutumnYellow" },
  NotifyWARNTitle = { link = "AutumnYellow" },
  IlluminatedWordText = { link = "LspReferenceText" },
  IlluminatedWordRead = { link = "LspReferenceRead" },
  IlluminatedWordWrite = { link = "LspReferenceWrite" },
  TSRainbowRed = { fg = colors.red },
  TSRainbowOrange = { fg = colors.orange },
  TSRainbowYellow = { fg = colors.yellow },
  TSRainbowGreen = { fg = colors.green },
  TSRainbowBlue = { fg = colors.blue },
  TSRainbowViolet = { fg = colors.purple },
  TSRainbowCyan = { fg = colors.aqua },
  RainbowDelimiterRed = { fg = colors.red },
  RainbowDelimiterOrange = { fg = colors.orange },
  RainbowDelimiterYellow = { fg = colors.yellow },
  RainbowDelimiterGreen = { fg = colors.green },
  RainbowDelimiterBlue = { fg = colors.blue },
  RainbowDelimiterViolet = { fg = colors.purple },
  RainbowDelimiterCyan = { fg = colors.aqua },
  DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
  DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
  DapUIBreakpointsCurrentLine = { link = "AutumnYellow" },
  DapUIBreakpointsDisabledLine = { link = "AutumnGray" },
  DapUIBreakpointsInfo = { link = "AutumnAqua" },
  DapUIBreakpointsLine = { link = "AutumnYellow" },
  DapUIBreakpointsPath = { link = "AutumnBlue" },
  DapUICurrentFrameName = { link = "AutumnPurple" },
  DapUIDecoration = { link = "AutumnPurple" },
  DapUIEndofBuffer = { link = "EndOfBuffer" },
  DapUIFloatBorder = { link = "AutumnAqua" },
  DapUILineNumber = { link = "AutumnYellow" },
  DapUIModifiedValue = { link = "AutumnRed" },
  DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
  DapUIRestart = { fg = colors.green, bg = colors.bg1 },
  DapUIScope = { link = "AutumnBlue" },
  DapUISource = { link = "AutumnFg1" },
  DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
  DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
  DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
  DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
  DapUIStop = { fg = colors.red, bg = colors.bg1 },
  DapUIStoppedThread = { link = "AutumnBlue" },
  DapUIThread = { link = "AutumnBlue" },
  DapUIType = { link = "AutumnOrange" },
  DapUIUnavailable = { link = "AutumnGray" },
  DapUIWatchesEmpty = { link = "AutumnGray" },
  DapUIWatchesError = { link = "AutumnRed" },
  DapUIWatchesValue = { link = "AutumnYellow" },
  DapUIWinSelect = { link = "AutumnYellow" },
  NeogitDiffDelete = { link = "DiffDelete" },
  NeogitDiffAdd = { link = "DiffAdd" },
  NeogitHunkHeader = { link = "WinBar" },
  NeogitHunkHeaderHighlight = { link = "WinBarNC" },
  DiffviewStatusModified = { link = "AutumnGreenBold" },
  DiffviewFilePanelInsertions = { link = "AutumnGreenBold" },
  DiffviewFilePanelDeletions = { link = "AutumnRedBold" },
  MiniAnimateCursor = { reverse = true, nocombine = true },
  MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
  MiniClueBorder = { link = "FloatBorder" },
  MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
  MiniClueDescSingle = { link = "NormalFloat" },
  MiniClueNextKey = { link = "DiagnosticFloatingHint" },
  MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
  MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
  MiniClueTitle = { link = "FloatTitle" },
  MiniCompletionActiveParameter = { underline = true },
  MiniCursorword = { underline = true },
  MiniCursorwordCurrent = { underline = true },
  MiniDepsChangeAdded = { link = "AutumnGreen" },
  MiniDepsChangeRemoved = { link = "AutumnRed" },
  MiniDepsHint = { link = "DiagnosticHint" },
  MiniDepsInfo = { link = "DiagnosticInfo" },
  MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
  MiniDepsPlaceholder = { link = "Comment" },
  MiniDepsTitle = { link = "Title" },
  MiniDepsTitleError = { link = "DiffDelete" },
  MiniDepsTitleSame = { link = "DiffChange" },
  MiniDepsTitleUpdate = { link = "DiffAdd" },
  MiniDiffOverAdd = { link = "DiffAdd" },
  MiniDiffOverChange = { link = "DiffText" },
  MiniDiffOverContext = { link = "DiffChange" },
  MiniDiffOverDelete = { link = "DiffDelete" },
  MiniDiffSignAdd = { link = "AutumnGreen" },
  MiniDiffSignChange = { link = "AutumnAqua" },
  MiniDiffSignDelete = { link = "AutumnRed" },
  MiniFilesBorder = { link = "FloatBorder" },
  MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
  MiniFilesCursorLine = { bg = colors.bg2 },
  MiniFilesDirectory = { link = "Directory" },
  MiniFilesFile = { link = "AutumnFg1" },
  MiniFilesNormal = { link = "NormalFloat" },
  MiniFilesTitle = { link = "FloatTitle" },
  MiniFilesTitleFocused = { link = "AutumnOrangeBold" },
  MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red },
  MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow },
  MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue },
  MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua },
  MiniIconsAzure = { link = "AutumnBlue" },
  MiniIconsBlue = { link = "AutumnBlue" },
  MiniIconsCyan = { link = "AutumnAqua" },
  MiniIconsGreen = { link = "AutumnGreen" },
  MiniIconsGrey = { link = "AutumnFg0" },
  MiniIconsOrange = { link = "AutumnOrange" },
  MiniIconsPurple = { link = "AutumnPurple" },
  MiniIconsRed = { link = "AutumnRed" },
  MiniIconsYellow = { link = "AutumnYellow" },
  MiniIndentscopeSymbol = { link = "AutumnGray" },
  MiniIndentscopeSymbolOff = { link = "AutumnYellow" },
  MiniJump = { link = "AutumnOrangeUnderline" },
  MiniJump2dDim = { link = "AutumnGray" },
  MiniJump2dSpot = { fg = colors.orange, nocombine = true },
  MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
  MiniJump2dSpotUnique = { fg = colors.yellow, nocombine = true },
  MiniMapNormal = { link = "NormalFloat" },
  MiniMapSymbolCount = { link = "Special" },
  MiniMapSymbolLine = { link = "Title" },
  MiniMapSymbolView = { link = "Delimiter" },
  MiniNotifyBorder = { link = "FloatBorder" },
  MiniNotifyNormal = { link = "NormalFloat" },
  MiniNotifyTitle = { link = "FloatTitle" },
  MiniOperatorsExchangeFrom = { link = "IncSearch" },
  MiniPickBorder = { link = "FloatBorder" },
  MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
  MiniPickBorderText = { link = "FloatTitle" },
  MiniPickIconDirectory = { link = "Directory" },
  MiniPickIconFile = { link = "MiniPickNormal" },
  MiniPickHeader = { link = "DiagnosticFloatingHint" },
  MiniPickMatchCurrent = { bg = colors.bg2 },
  MiniPickMatchMarked = { link = "Visual" },
  MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
  MiniPickNormal = { link = "NormalFloat" },
  MiniPickPreviewLine = { link = "CursorLine" },
  MiniPickPreviewRegion = { link = "IncSearch" },
  MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
  MiniStarterCurrent = { nocombine = true },
  MiniStarterFooter = { link = "AutumnGray" },
  MiniStarterHeader = { link = "Title" },
  MiniStarterInactive = { link = "Comment" },
  MiniStarterItem = { link = "Normal" },
  MiniStarterItemBullet = { link = "Delimiter" },
  MiniStarterItemPrefix = { link = "WarningMsg" },
  MiniStarterSection = { link = "Delimiter" },
  MiniStarterQuery = { link = "MoreMsg" },
  MiniStatuslineDevinfo = { link = "StatusLine" },
  MiniStatuslineFileinfo = { link = "StatusLine" },
  MiniStatuslineFilename = { link = "StatusLineNC" },
  MiniStatuslineInactive = { link = "StatusLineNC" },
  MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow },
  MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue },
  MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1 },
  MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua },
  MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red },
  MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green },
  MiniSurround = { link = "IncSearch" },
  MiniTablineCurrent = { fg = colors.green, bg = colors.bg1 },
  MiniTablineFill = { link = "TabLineFill" },
  MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1 },
  MiniTablineModifiedCurrent = {
    fg = colors.bg1,
    bg = colors.green,
  },
  MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4 },
  MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1 },
  MiniTablineTabpagesection = { link = "Search" },
  MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1 },
  MiniTestEmphasis = {},
  MiniTestFail = { link = "AutumnRedBold" },
  MiniTestPass = { link = "AutumnGreenBold" },
  MiniTrailspace = { bg = colors.red },
  ["@comment"] = { link = "AutumnGray" },
  ["@none"] = { bg = "NONE", fg = "NONE" },
  ["@preproc"] = { link = "PreProc" },
  ["@define"] = { link = "Define" },
  ["@operator"] = { link = "Operator" },
  ["@punctuation.delimiter"] = { link = "Delimiter" },
  ["@punctuation.bracket"] = { link = "Delimiter" },
  ["@punctuation.special"] = { link = "Delimiter" },
  ["@string"] = { link = "String" },
  ["@string.regex"] = { link = "String" },
  ["@string.regexp"] = { link = "String" },
  ["@string.escape"] = { link = "SpecialChar" },
  ["@string.special"] = { link = "SpecialChar" },
  ["@string.special.path"] = { link = "Underlined" },
  ["@string.special.symbol"] = { link = "Identifier" },
  ["@string.special.url"] = { link = "Underlined" },
  ["@character"] = { link = "Character" },
  ["@character.special"] = { link = "SpecialChar" },
  ["@boolean"] = { link = "Boolean" },
  ["@number"] = { link = "Number" },
  ["@number.float"] = { link = "Float" },
  ["@float"] = { link = "Float" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Special" },
  ["@function.call"] = { link = "Function" },
  ["@function.macro"] = { link = "Macro" },
  ["@function.method"] = { link = "Function" },
  ["@method"] = { link = "Function" },
  ["@method.call"] = { link = "Function" },
  ["@constructor"] = { link = "Special" },
  ["@parameter"] = { link = "Identifier" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.conditional"] = { link = "Conditional" },
  ["@keyword.debug"] = { link = "Debug" },
  ["@keyword.directive"] = { link = "PreProc" },
  ["@keyword.directive.define"] = { link = "Define" },
  ["@keyword.exception"] = { link = "Exception" },
  ["@keyword.function"] = { link = "Keyword" },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.operator"] = { link = "AutumnRed" },
  ["@keyword.repeat"] = { link = "Repeat" },
  ["@keyword.return"] = { link = "Keyword" },
  ["@keyword.storage"] = { link = "StorageClass" },
  ["@conditional"] = { link = "Conditional" },
  ["@repeat"] = { link = "Repeat" },
  ["@debug"] = { link = "Debug" },
  ["@label"] = { link = "Label" },
  ["@include"] = { link = "Include" },
  ["@exception"] = { link = "Exception" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { link = "Type" },
  ["@type.definition"] = { link = "Typedef" },
  ["@type.qualifier"] = { link = "Type" },
  ["@storageclass"] = { link = "StorageClass" },
  ["@attribute"] = { link = "PreProc" },
  ["@field"] = { link = "Identifier" },
  ["@property"] = { link = "Identifier" },
  ["@variable"] = { link = "AutumnFg1" },
  ["@variable.builtin"] = { link = "Special" },
  ["@variable.member"] = { link = "Identifier" },
  ["@variable.parameter"] = { link = "Identifier" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Special" },
  ["@constant.macro"] = { link = "Define" },
  ["@markup"] = { link = "AutumnFg1" },
  ["@markup.strong"] = {},
  ["@markup.italic"] = { link = "@text.emphasis" },
  ["@markup.underline"] = {},
  ["@markup.strikethrough"] = {},
  ["@markup.heading"] = { link = "Title" },
  ["@markup.raw"] = { link = "String" },
  ["@markup.math"] = { link = "Special" },
  ["@markup.environment"] = { link = "Macro" },
  ["@markup.environment.name"] = { link = "Type" },
  ["@markup.link"] = { link = "Underlined" },
  ["@markup.link.label"] = { link = "SpecialChar" },
  ["@markup.list"] = { link = "Delimiter" },
  ["@markup.list.checked"] = { link = "AutumnGreen" },
  ["@markup.list.unchecked"] = { link = "AutumnGray" },
  ["@comment.todo"] = { link = "AutumnGray" },
  ["@comment.note"] = { link = "AutumnGray" },
  ["@comment.warning"] = { link = "WarningMsg" },
  ["@comment.error"] = { link = "ErrorMsg" },
  ["@diff.plus"] = { link = "diffAdded" },
  ["@diff.minus"] = { link = "diffRemoved" },
  ["@diff.delta"] = { link = "diffChanged" },
  ["@module"] = { link = "AutumnFg1" },
  ["@namespace"] = { link = "AutumnFg1" },
  ["@symbol"] = { link = "Identifier" },
  ["@text"] = { link = "AutumnFg1" },
  ["@text.strong"] = {},
  ["@text.emphasis"] = {},
  ["@text.underline"] = {},
  ["@text.strike"] = {},
  ["@text.title"] = { link = "Title" },
  ["@text.literal"] = { link = "String" },
  ["@text.uri"] = { link = "Underlined" },
  ["@text.math"] = { link = "Special" },
  ["@text.environment"] = { link = "Macro" },
  ["@text.environment.name"] = { link = "Type" },
  ["@text.reference"] = { link = "Constant" },
  ["@text.todo"] = { link = "Todo" },
  ["@text.todo.checked"] = { link = "AutumnGreen" },
  ["@text.todo.unchecked"] = { link = "AutumnGray" },
  ["@text.note"] = { link = "SpecialComment" },
  ["@text.note.comment"] = { fg = colors.purple },
  ["@text.warning"] = { link = "WarningMsg" },
  ["@text.danger"] = { link = "ErrorMsg" },
  ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red },
  ["@text.diff.add"] = { link = "diffAdded" },
  ["@text.diff.delete"] = { link = "diffRemoved" },
  ["@tag"] = { link = "Tag" },
  ["@tag.attribute"] = { link = "Identifier" },
  ["@tag.delimiter"] = { link = "Delimiter" },
  ["@punctuation"] = { link = "Delimiter" },
  ["@macro"] = { link = "Macro" },
  ["@structure"] = { link = "Structure" },
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.comment"] = { link = "AutumnGray" },
  ["@lsp.type.decorator"] = { link = "@macro" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { link = "@constant" },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.interface"] = { link = "@constructor" },
  ["@lsp.type.macro"] = { link = "@macro" },
  ["@lsp.type.method"] = { link = "@method" },
  ["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
  ["@lsp.type.namespace"] = { link = "@namespace" },
  ["@lsp.type.parameter"] = { link = "@parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.typeParameter"] = { link = "@type.definition" },
  ["@lsp.type.variable"] = { link = "@variable" },
}

function M.load()
  vim.o.background = "dark"

  if vim.g.colors_name then vim.cmd.hi("clear") end
  vim.g.colors_name = "autumn_night"
  vim.o.termguicolors = true

  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end

  local term_colors = {
    colors.bg0,
    colors.neutral_red,
    colors.neutral_green,
    colors.neutral_yellow,
    colors.neutral_blue,
    colors.neutral_purple,
    colors.neutral_aqua,
    colors.fg4,
    colors.gray,
    colors.red,
    colors.green,
    colors.yellow,
    colors.blue,
    colors.purple,
    colors.aqua,
    colors.fg1,
  }

  for index, value in ipairs(term_colors) do
    vim.g["terminal_color_" .. index - 1] = value
  end
end

return M
